spring.application.name=userservice

# telling spring kafka, that the messages are gonna have key of string, value of bytearray
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
server.port=8085